/**
 * Export Utilities for Pulse Web Application
 * Handles data export to CSV, Excel (.xlsx compatible), and PDF report formats.
 */

export interface ExportColumn {
  header: string;
  key: string;
}

/**
 * Escapes strings for CSV format
 */
function escapeCSVCell(val: any): string {
  if (val === null || val === undefined) return '""';
  const str = String(val).replace(/"/g, '""');
  if (str.includes(',') || str.includes('\n') || str.includes('"')) {
    return `"${str}"`;
  }
  return `"${str}"`;
}

/**
 * Download CSV File
 */
export function exportToCSV(
  filename: string,
  data: Record<string, any>[],
  columns?: ExportColumn[]
): void {
  if (!data || data.length === 0) return;

  const cols = columns || Object.keys(data[0]).map(k => ({ header: k, key: k }));
  const headerRow = cols.map(c => escapeCSVCell(c.header)).join(',');
  
  const dataRows = data.map(row => {
    return cols.map(c => escapeCSVCell(row[c.key])).join(',');
  });

  const csvContent = [headerRow, ...dataRows].join('\r\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Download Excel-compatible (.xlsx / .csv format with BOM)
 */
export function exportToExcel(
  filename: string,
  data: Record<string, any>[],
  columns?: ExportColumn[]
): void {
  if (!data || data.length === 0) return;

  const cols = columns || Object.keys(data[0]).map(k => ({ header: k, key: k }));
  const headerRow = cols.map(c => escapeCSVCell(c.header)).join('\t');

  const dataRows = data.map(row => {
    return cols.map(c => escapeCSVCell(row[c.key])).join('\t');
  });

  const tsvContent = [headerRow, ...dataRows].join('\r\n');
  const blob = new Blob(['\uFEFF' + tsvContent], { type: 'application/vnd.ms-excel;charset=utf-8;' });

  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.xls') || filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export data as styled PDF report document
 */
export function exportToPDF(
  filename: string,
  title: string,
  data: Record<string, any>[],
  columns?: ExportColumn[]
): void {
  if (!data || data.length === 0) return;

  const cols = columns || Object.keys(data[0]).map(k => ({ header: k, key: k }));

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF reports.');
    return;
  }

  const tableHeaderHtml = cols.map(c => `<th style="border: 1px solid #e5e7eb; padding: 8px 12px; background-color: #f3f4f6; text-align: left; font-size: 11px; font-weight: 700; text-transform: uppercase; font-family: monospace;">${c.header}</th>`).join('');
  
  const tableRowsHtml = data.map((row, i) => {
    const bg = i % 2 === 0 ? '#ffffff' : '#f9fafb';
    const cells = cols.map(c => `<td style="border: 1px solid #e5e7eb; padding: 8px 12px; font-size: 12px; background-color: ${bg};">${String(row[c.key] ?? '')}</td>`).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - ${filename}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 24px; color: #111827; }
          h1 { font-size: 20px; font-weight: 800; margin-bottom: 4px; }
          .subtitle { font-size: 12px; color: #6b7280; font-family: monospace; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          .footer { margin-top: 32px; font-size: 10px; color: #9ca3af; font-family: monospace; text-align: right; border-top: 1px solid #e5e7eb; padding-top: 8px; }
          @media print {
            body { padding: 0; }
            @page { margin: 1.5cm; }
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="subtitle">Generated by Pulse Platform &bull; ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</div>
        <table>
          <thead>
            <tr>${tableHeaderHtml}</tr>
          </thead>
          <tbody>
            ${tableRowsHtml}
          </tbody>
        </table>
        <div class="footer">Confidential &bull; Pulse Executive Brief</div>
        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
